capacity_index:
    path:     /
    defaults: { _controller: "AppBundle:Capacidad:index" }
    methods:  GET

capacity_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Capacidad:show" }
    methods:  GET

capacity_new:
    path:     /new
    defaults: { _controller: "AppBundle:Capacidad:new" }
    methods:  [GET, POST]

capacity_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Capacidad:edit" }
    methods:  [GET, POST]

capacity_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Capacidad:delete" }
    methods:  DELETE