champ_index:
    path:     /
    defaults: { _controller: "AppBundle:Campeonato:index" }
    methods:  GET

champ_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Campeonato:show" }
    methods:  GET

champ_new:
    path:     /new
    defaults: { _controller: "AppBundle:Campeonato:new" }
    methods:  [GET, POST]

champ_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Campeonato:edit" }
    methods:  [GET, POST]

champ_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Campeonato:delete" }
    methods:  DELETE
