courtes_index:
    path:     /
    defaults: { _controller: "AppBundle:Cancha:index" }
    methods:  GET

courtes_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cancha:show" }
    methods:  GET

courtes_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cancha:new" }
    methods:  [GET, POST]

courtes_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cancha:edit" }
    methods:  [GET, POST]

courtes_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cancha:delete" }
    methods:  DELETE