services_index:
    path:     /
    defaults: { _controller: "AppBundle:Servicio:index" }
    methods:  GET

services_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Servicio:show" }
    methods:  GET

services_new:
    path:     /new
    defaults: { _controller: "AppBundle:Servicio:new" }
    methods:  [GET, POST]

services_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Servicio:edit" }
    methods:  [GET, POST]

services_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Servicio:delete" }
    methods:  DELETE