app_champ:
    resource: "@AppBundle/Resources/config/routing/championship.yml"
    prefix:   /championships

app_complex:
    resource: "@AppBundle/Resources/config/routing/complex.yml"
    prefix:   /complex

app_type_courtes:
    resource: "@AppBundle/Resources/config/routing/type_courtes.yml"
    prefix:   /type-courtes

app_courtes:
    resource: "@AppBundle/Resources/config/routing/courtes.yml"
    prefix:   /courtes

app_default:
    path:     /index
    defaults: { _controller: AppBundle:Index:index }
    methods: GET

app_complejos:
    path:     /complejos
    defaults: { _controller: AppBundle:Index:comp }

app_campeonatos:
    path:     /campeonatos
    defaults: { _controller: AppBundle:Index:camp }

app_descripcion:
    path:     /complejos/decripcion/{id}
    defaults: { _controller: AppBundle:Index:desc_cancha }

app_contacto:
    path:     /contacto
    defaults: { _controller: AppBundle:Index:contact }

app_descrip:
    path:     /complejos/decripcion/calendario
    defaults: { _controller: AppBundle:Index:desc_cancha }

app_lang:
    path:     /lang/{_locale}
    defaults: { _controller: AppBundle:Index:lang }

s_admin:
    path:     /admin-s
    defaults: {_controller: AppBundle:Admin:super}
    methods: GET

admin:
    path:     /admin
    defaults: {_controller: AppBundle:Admin:admin}
    methods: GET