AppBundle\Entity\Complejo:
    type: entity
    table: complejo
    indexes:
        id_user:
            columns:
                - id_user
    id:
        idComp:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_comp
            generator:
                strategy: IDENTITY
    fields:
        nameComp:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: name_comp
        direComp:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: dire_comp
        phonComp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: phon_comp
        mailComp:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: mail_comp
        descripComp:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: descrip_comp
        urlComp:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: url_comp
        timestamp:
            type: datetime
            nullable: true
    manyToOne:
        idUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        idRede:
            targetEntity: Redes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: idComp
            joinTable:
                name: comp_redes
                joinColumns:
                    -
                        name: id_comp
                        referencedColumnName: id_comp
                inverseJoinColumns:
                    -
                        name: id_rede
                        referencedColumnName: id_rede
            orderBy: null
        idServ:
            targetEntity: Servicio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: idComp
            joinTable:
                name: comp_serv
                joinColumns:
                    -
                        name: id_comp
                        referencedColumnName: id_comp
                inverseJoinColumns:
                    -
                        name: id_serv
                        referencedColumnName: id_Serv
            orderBy: null
    lifecycleCallbacks: {  }
