AppBundle\Entity\FosUser:
    type: entity
    table: fos_user
    uniqueConstraints:
        UNIQ_957A647992FC23A8:
            columns:
                - username_canonical
        UNIQ_957A6479A0D96FBF:
            columns:
                - email_canonical
        UNIQ_957A6479C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameUser:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: name_user
        dniUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dni_user
        fnacUser:
            type: date
            nullable: true
            column: fnac_user
        direUser:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: dire_user
        phonUser:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: phon_user
    lifecycleCallbacks: {  }
