AppBundle\Entity\HoraFecha:
    type: entity
    table: hora_fecha
    indexes:
        id_hora:
            columns:
                - id_hora
    id:
        idHofe:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_hofe
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: date
            nullable: true
    manyToOne:
        idHora:
            targetEntity: Hora
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_hora:
                    referencedColumnName: id_hora
            orphanRemoval: false
    lifecycleCallbacks: {  }
