AppBundle\Entity\Reserva:
    type: entity
    table: reserva
    indexes:
        id_canch:
            columns:
                - id_canch
        id_usua:
            columns:
                - id_usua
        id_hora:
            columns:
                - id_hora
    id:
        idRese:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_rese
            generator:
                strategy: IDENTITY
    fields:
        timestamp:
            type: datetime
            nullable: true

        fecha_reserva:
            type: date
            nullable: false
    manyToOne:
        idCanch:
            targetEntity: Cancha
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_canch:
                    referencedColumnName: id_canch
            orphanRemoval: false
        idHora:
            targetEntity: Hora
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_hora:
                    referencedColumnName: id_hora
            orphanRemoval: false
        idUsua:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usua:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
