AppBundle\Entity\Semana:
    type: entity
    table: semana
    id:
        idDia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_dia
            generator:
                strategy: IDENTITY
    fields:
        nomDia:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nom_dia
    lifecycleCallbacks: {  }
